esp8266:
  board: d1_mini

esphome:
  name: turn-to-middle
  on_boot:
    priority: -100
    then:
      - servo.write:
          id: vent_servo
          level: 0

servo:
  - id: vent_servo
    output: vent_servo_output

output:
  - platform: esp8266_pwm
    id: vent_servo_output
    pin: D5
    frequency: 50 Hz
    
captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

api:
    
ota:

logger:
  level: INFO
