substitutions:
  name: yet-another-smart-vent

esphome:
  name: $name
#  name_add_mac_suffix: true

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret development_static_ip
    gateway: !secret gateway
    subnet: !secret subnet
#  ap:
#    ssid: $upper_name
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
    
light:
  - platform: binary
    name: "ESPHome Development LED"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: GPIO2
    inverted: true
    
web_server:

api:
    
ota:

logger:
  level: NONE
