substitutions:
  name: yet-another-smart-vent

globals:
  - id: move_servo_to_position
    type: float
    initial_value: '0'
  - id: servo_distance_to_move
    type: float
    initial_value: '0.01'
  - id: previous_potentiometer_value1
    type: int
    initial_value: '999999'
  - id: previous_potentiometer_value2
    type: int
    initial_value: '999998'
  - id: previous_potentiometer_value3
    type: int
    initial_value: '999996'
  - id: max_closed_position
    type: float
    initial_value: '1'
  - id: max_opened_position
    type: float
    initial_value: '-1'
  - id: closed_position
    type: float
    initial_value: '0'
  - id: closed_potentionmeter_position
    type: int
    initial_value: '0'
  - id: opened_position
    type: float
    initial_value: '0'
  - id: opened_potentionmeter_position
    type: int
    initial_value: '0'
  - id: position_error_tolerance
    type: float
    initial_value: '1.5'

esp8266:
  board: d1_mini

esphome:
  name: $name
  on_boot:
    priority: -100
    then:
    - servo.write:
        id: vent_servo
        level: !lambda 'return id(move_servo_to_position);'
    - delay: 1s
    - while:
        condition:
          lambda: 'return id(move_servo_to_position) < id(max_closed_position);'
        then:
          - servo.write:
              id: vent_servo
              level: !lambda 'return id(move_servo_to_position);'
          - delay: 50ms
          - globals.set:
              id: move_servo_to_position
              value: !lambda 'return id(move_servo_to_position) + id(servo_distance_to_move);'
          - globals.set:
              id: previous_potentiometer_value3
              value: !lambda 'return id(previous_potentiometer_value2);'
          - globals.set:
              id: previous_potentiometer_value2
              value: !lambda 'return id(previous_potentiometer_value1);'
          - globals.set:
              id: previous_potentiometer_value1
              value: !lambda 'return analogRead(A0);'
          - lambda: 'ESP_LOGD("custom", "%d | %d | %d", id(previous_potentiometer_value1), id(previous_potentiometer_value2), id(previous_potentiometer_value3));'
          - if:
              condition:
                lambda: |-
                  const int current_position = id(previous_potentiometer_value1);
                  const int upper_tolerance1 = id(previous_potentiometer_value2) + id(position_error_tolerance);
                  const int lower_tolerance1 = id(previous_potentiometer_value2) - id(position_error_tolerance);
                  const int upper_tolerance2 = id(previous_potentiometer_value3); + id(position_error_tolerance);
                  const int lower_tolerance2 = id(previous_potentiometer_value3); - id(position_error_tolerance);
                  return current_position >= lower_tolerance1 && current_position <= upper_tolerance1
                    && current_position >= lower_tolerance2 && current_position <= upper_tolerance2;
              then: 
                - logger.log: 'opened | TRUE!'
                - globals.set:
                    id: max_closed_position
                    value: !lambda 'return id(move_servo_to_position);'
                - globals.set:
                    id: closed_position
                    value: !lambda 'return id(move_servo_to_position);'
                - globals.set:
                    id: closed_potentionmeter_position
                    value: !lambda 'return id(previous_potentiometer_value1);'
    - globals.set:
        id: move_servo_to_position
        value: '0'
    - delay: 250ms
    - servo.write:
        id: vent_servo
        level: !lambda 'return id(move_servo_to_position);'
    - globals.set:
        id: previous_potentiometer_value3
        value: '999997'
    - globals.set:
        id: previous_potentiometer_value2
        value: '999998'
    - globals.set:
        id: previous_potentiometer_value1
        value: '999999'
    # - delay: 1s
    - while:
        condition:
          lambda: 'return id(move_servo_to_position) > id(max_opened_position);'
        then:
          - servo.write:
              id: vent_servo
              level: !lambda 'return id(move_servo_to_position);'
          - delay: 50ms
          - globals.set:
              id: move_servo_to_position
              value: !lambda 'return id(move_servo_to_position) - id(servo_distance_to_move);'
          - globals.set:
              id: previous_potentiometer_value3
              value: !lambda 'return id(previous_potentiometer_value2);'
          - globals.set:
              id: previous_potentiometer_value2
              value: !lambda 'return id(previous_potentiometer_value1);'
          - globals.set:
              id: previous_potentiometer_value1
              value: !lambda 'return analogRead(A0);'
          - lambda: 'ESP_LOGD("custom", "%d | %d | %d", id(previous_potentiometer_value1), id(previous_potentiometer_value2), id(previous_potentiometer_value3));'
          - if:
              condition:
                lambda: |-
                  const int current_position = id(previous_potentiometer_value1);
                  const int upper_tolerance1 = id(previous_potentiometer_value2) + id(position_error_tolerance);
                  const int lower_tolerance1 = id(previous_potentiometer_value2) - id(position_error_tolerance);
                  const int upper_tolerance2 = id(previous_potentiometer_value3); + id(position_error_tolerance);
                  const int lower_tolerance2 = id(previous_potentiometer_value3); - id(position_error_tolerance);
                  return current_position >= lower_tolerance1 && current_position <= upper_tolerance1
                    && current_position >= lower_tolerance2 && current_position <= upper_tolerance2;
              then: 
                - logger.log: 'closed | TRUE!'
                - globals.set:
                    id: max_opened_position
                    value: !lambda 'return id(move_servo_to_position);'
                - globals.set:
                    id: opened_position
                    value: !lambda 'return id(move_servo_to_position);'
                - globals.set:
                    id: opened_potentionmeter_position
                    value: !lambda 'return id(previous_potentiometer_value1);'
    - servo.detach: vent_servo
    - delay: 1s
    - servo.detach: vent_servo
    - lambda: 'ESP_LOGD("custom", "closed_position: %f | closed_potentionmeter_position: %d", id(closed_position), id(closed_potentionmeter_position));'
    - lambda: 'ESP_LOGD("custom", "opened_position: %f | opened_potentionmeter_position: %d", id(opened_position), id(opened_potentionmeter_position));'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret development_static_ip
    gateway: !secret gateway
    subnet: !secret subnet
#  ap:
#    ssid: $upper_name
    
# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

mdns:
  disabled: false

servo:
  - id: vent_servo
    output: vent_servo_output
    transition_length: 3s
    
# sensor:
#   - platform: adc
#     pin: A0
#     name: Potentiometer
#     update_interval: 50ms

output:
  - platform: esp8266_pwm
    id: vent_servo_output
    pin: D3
    frequency: 50 Hz

#web_server:

#api:
    
ota:

logger:
  level: DEBUG
