substitutions:
  name: yet-another-smart-vent

esphome:
  name: $name
#  name_add_mac_suffix: true

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret development_static_ip
    gateway: !secret gateway
    subnet: !secret subnet
#  ap:
#    ssid: $upper_name
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

number:
  - platform: template
    name: Servo Control
    min_value: -100
    max_value: 50
    step: 1
    set_action:
      then:
        - servo.write:
            id: vent_servo
            level: !lambda 'return x / 100.0;'

servo:
  - id: vent_servo
    output: pwm_output
    auto_detach_time: 250ms
    transition_length: 25s
    
light:
  - platform: binary
    name: "ESPHome Development LED"
    output: light_output

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D3
    frequency: 50 Hz
  - id: light_output
    platform: gpio
    pin: GPIO2
    inverted: true
    
web_server:

api:
    
ota:

logger:
  level: NONE
