substitutions:
  name: yet-another-smart-vent

esphome:
  name: $name
#  name_add_mac_suffix: true
  on_boot:
    then:
    - lambda: |-
        ESP_LOGD("custom", "Hello World!!!!");

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret development_static_ip
    gateway: !secret gateway
    subnet: !secret subnet
#  ap:
#    ssid: $upper_name
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

servo:
  - id: vent_servo
    output: vent_servo_output
    transition_length: 3s
    auto_detach_time: 250ms

output:
  - platform: esp8266_pwm
    id: vent_servo_output
    pin: D3
    frequency: 50 Hz

web_server:

api:
    
ota:

logger:
  level: DEBUG
