substitutions:
  name: yet-another-smart-vent

globals:
  - id: move_servo_to_position
    type: float
    initial_value: '0'

esp8266:
  board: d1_mini

esphome:
  name: $name
  on_boot:
    priority: -100
    then:
    - while:
        condition:
          lambda: |-
            return id(move_servo_to_position) <= 0.75;
        then:
          - servo.write:
              id: vent_servo
              level: !lambda 'return id(move_servo_to_position);'
          - globals.set:
              id: move_servo_to_position
              value: !lambda 'return id(move_servo_to_position) + 0.01;'
          - delay: 25ms
    - while:
        condition:
          lambda: |-
            return id(move_servo_to_position) >= -1;
        then:
          - servo.write:
              id: vent_servo
              level: !lambda 'return id(move_servo_to_position);'
          - globals.set:
              id: move_servo_to_position
              value: !lambda 'return id(move_servo_to_position) - 0.01;'
          - delay: 25ms

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret development_static_ip
    gateway: !secret gateway
    subnet: !secret subnet
#  ap:
#    ssid: $upper_name
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

servo:
  - id: vent_servo
    output: vent_servo_output
    transition_length: 3s
    # auto_detach_time: 250ms

output:
  - platform: esp8266_pwm
    id: vent_servo_output
    pin: D3
    frequency: 50 Hz

web_server:

api:
    
ota:

logger:
  level: DEBUG
