globals:
  - id: position_to_move_servo_to
    type: float
    initial_value: '0'
  - id: servo_distance_to_move
    type: float
    initial_value: '0.01'

esp8266:
  board: d1_mini

esphome:
  name: yet-another-smart-vent
  on_boot:
    priority: -100
    then:
    - servo.write:
        id: vent_servo
        level: 0
    - delay: 225ms
    - while:
        condition:
          lambda: 'return !id(closed_limit_switch).state;'
        then:
            - globals.set:
                id: position_to_move_servo_to
                value: !lambda 'return id(position_to_move_servo_to) - id(servo_distance_to_move);'
            - servo.write:
                id: vent_servo
                level: !lambda 'return id(position_to_move_servo_to);'
            - delay: 75ms

binary_sensor:
  - platform: gpio
    pin: 15
    id: closed_limit_switch
    name: "Closed Limit Switch"
  
sensor:
  - platform: adc
    id: vent_servo_potentiometer
    pin: A0
    update_interval: 250ms

servo:
  - id: vent_servo
    output: vent_servo_output
    transition_length: 3s
    auto_detach_time: 200ms
    
output:
  - platform: esp8266_pwm
    id: vent_servo_output
    pin: D3
    frequency: 50 Hz
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret static_ip
    gateway: !secret gateway
    subnet: !secret subnet

web_server:

ota:
    
logger:
  level: DEBUG
